# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # PHP dependencies
  - package-ecosystem: "composer"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    rebase-strategy: "auto"
    #assignees:
    #  - "ArnaudLigny"
    reviewers:
      - "ArnaudLigny"
    versioning-strategy: lockfile-only
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
