# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "ArnaudLigny"
    commit-message:
      prefix: "deps prod"
      prefix-development: "deps dev"
      include: "scope"
    labels:
      - "dependencies"
    rebase-strategy: "auto"
    reviewers:
      - "ArnaudLigny"
    versioning-strategy: lockfile-only
