language: php
# PHP versions
php:
  - 5.6
  - 7.0
# faster builds on new travis setup not using sudo
sudo: false
# cache vendor dirs
cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
# update composer it-self
install:
  - composer self-update
# install package
before_script:
  - composer install --no-interaction
  - mkdir -p build/logs
# run PHPUnit and export code coverage log
script:
  - phpunit -c ./ --coverage-text --coverage-clover build/logs/clover.xml
# run coveralls
after_script:
  - php vendor/bin/coveralls -v
# deploy
before_deploy: "vendor/bin/box build"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "phpoole.phar"
  skip_cleanup: true
  overwrite: true
#  on:
#    tags: true
